---
- name: Configure cron
  hosts: all

  tasks:
  - name: Configure Periodic Execution of AIDE
    cron:
      name: run AIDE check
      minute: 5
      hour: 4
      weekday: 0
      user: root
      job: /usr/sbin/aide --check

...
